### PR TITLE
Added fontawesome alt-text and titles for accessibility

### PR DESCRIPTION
**Pull request by chbrown13**
Pull request to make the fontawesome icons more accessible adding alt-text and titles for tooltips for issue #120

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hi Chris,

Nice to see this - can you change the tables.js alts that say value to read “Index” ? This better describes the purpose of the link and the author name/email is in the previous column.

This appears to match the document I found about how to do it, but I am curious if you tested it in a screen reader to see if there are other problems or improvements that need to be made?

—Michael

**Comment by chbrown13** [comment]
Hi, unfortunately this was not tested with a screen reader but only for tooltip text when hovering with the mouse. Can try using a screen reader to see if it works.

**Comment by mpdehaan** [comment]
if it also gives tool tips, I’m ok with trusting it.

that’s kind of more important use case wise anyway, thanks!

**Comment by mpdehaan** [comment]
merged thanks, this helps usability quite a bit, much appreciated!

**Pull request merged**
